<?php
/**
 * @var $block \Customcode\HomeSearch\Block\Home\Search
 */
?>
<!-- <div>
	<?php //echo $block->searchProduct() ?>
	<?php //echo __('Hello Customcode_HomeSearch::home/search.phtml') ?>
</div> -->

<?php

use function GuzzleHttp\json_decode;

$json = file_get_contents("./searchitems/category.json");
$list_category = json_decode($json);

$json = file_get_contents("./searchitems/brand_only.json");
$list_brand_only = json_decode($json);

$json = file_get_contents("./searchitems/model.json");
$list_model = json_decode($json);

$json = file_get_contents("./searchitems/year.json");
$list_year = json_decode($json);


$object_Manager = \Magento\Framework\App\ObjectManager::getInstance();
/* $helper = $object_Manager->get('\Radar\Sap\Helper\Data');
$marca_ws = $helper->get_marcas();
$anios_ws = $helper->get_anios(); */
 ?>

<?php /* if (is_object($marca_ws) && isset($marca_ws) && isset($marca_ws->ResponseStatus) && $marca_ws->ResponseStatus == 'Success' && $marca_ws->Response > 0) {
    $marcasManager = $object_Manager->get('\Magento\Eav\Model\Config');
    $marcas = $marcasManager->getAttribute('catalog_product', 'nipon_marca');
    $options = $marcas->getSource()->getAllOptions();
    foreach ($marca_ws->Response as $key => $value) {
        $keysearch = array_search($value->Marca, array_column($options, 'label'));
        if ($keysearch) {
            $value->Id = $options[$keysearch]['value'];
        } else {
            unset($marca_ws->Response[$key]);
        }
    } */
?>
    <div class="container">
        <div class="buscador-home">
            <span class="h3">BÚSQUEDA <strong>AVANZADA</strong></span>
            <form id="form-buscador" name="form-buscador" action="/catalogsearch/advanced/result/" method="GET">
                <select name="category" id="category">
                    <option value="" selected="selected">Tipo de repuesto</option>
                    <?php foreach ($list_category as $key => $value) { ?>
                        <option <?php if (isset($_GET['category']) && $_GET['category'] == $key) {
                                    echo 'selected="selected"';
                                } ?> value="<?php echo $key; ?>"><?php echo $value; ?></option>
                    <?php } ?>
                </select>
                <select name="nipon_marca" id="marca">
                    <option value="" selected="selected">Marca</option>
                    <?php foreach($list_brand_only as $key => $value){?>
                        <option <?php if (isset($_GET['nipon_marca']) && $_GET['nipon_marca'] == $key) {
                                    echo 'selected="selected"';
                                } ?> value="<?php echo $key; ?>"><?php echo $value; ?></option>
                    <?php }?>
                </select>
                <select name="nipon_modelo" id="modelo">
                    <option value="" selected="selected">Modelo</option>
                </select>
                <select name="nipon_years" id="year">
                    <option value="" selected="selected">Año</option>
                </select>
                <input type="submit" class="btn btn-buscador-home" value="Buscar">
            </form>
            <div class="uper-form">
                <div class="lds-roller">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
        </div>
    </div>

    <script>
        require(["jquery"], function($) {

                var waitForEl = function(selector, callback) {
                if (jQuery(selector).length) {
                    callback();
                } else {
                    setTimeout(function() {
                    waitForEl(selector, callback);
                    }, 100);
                }
                };

                waitForEl("#category", function() {
                    $("#category").val($("#category option:first").val());
                    $("#marca").val($("#marca option:first").val());
                    $("#modelo").val($("#modelo option:first").val());
                    $("#year").val($("#year option:first").val());
                });
                
            $('#category').change(function(e) {
                e.preventDefault();
                $('#marca').empty();
                $('#marca').append('<option value="">Marca</option>');
                $('.uper-form').fadeIn();
                if($(this).val() !=""){
                    $.ajax({
                        type: "GET",
                        url: "/searchitems/brand.json",
                        data: "data",
                        dataType: "json",
                        success: function(response) {
                            $.each(response, function(key, value) {
                                if (key == $('#category').val()) {
                                    $.each(value, function(k, brand) {
                                        $('#marca').append('<option value="' + key + '-' + brand + '">' + brand + '</option>');
                                    });
                                    
                                }
                            });
                            $('.uper-form').fadeOut();
                        }
                    });
                }else{
                    $.ajax({
                        type: "GET",
                        url: "/searchitems/brand_only.json",
                        data: "data",
                        dataType: "json",
                        success: function(response) {
                            $.each(response, function(key, value) { 
                                $('#marca').append('<option value="' + key + '">' + value + '</option>');
                            });
                            $('.uper-form').fadeOut();
                        }
                    });
                }
                
            });

            $('#marca').change(function(e) {
                e.preventDefault();
                $('#modelo').empty();
                $('#modelo').append('<option value="">Modelo</option>');
                $('.uper-form').fadeIn();
                if($('#category').val() != ''){
                    $.ajax({
                        type: "GET",
                        url: "/searchitems/model.json",
                        data: "data",
                        dataType: "json",
                        success: function(response) {
                            $.each(response, function(key, value) {
                                if (key == $('#marca').val()) {
                                    $.each(value, function(k, model) {
                                        $('#modelo').append('<option value="' + key + '-' + model + '">' + model + '</option>');
                                    });
                                }
                            });
                            $('.uper-form').fadeOut();
                        }
                    });
                }else{
                    $.ajax({
                        type: "GET",
                        url: "/searchitems/model_only.json",
                        data: "data",
                        dataType: "json",
                        success: function(response) {
                            $.each(response, function(key, value) {
                                if (key == $("#marca option:selected").html()) {
                                    $.each(value, function(k, model) {
                                        $('#modelo').append('<option value="' + k + '">' + model + '</option>');
                                    });
                                }
                            });
                            $('.uper-form').fadeOut();
                        }
                    });
                }
                
            });

            $('#modelo').change(function(e) {
                e.preventDefault();
                $('#year').empty();
                $('#year').append('<option value="">Año</option>');
                $('.uper-form').fadeIn();
                if($('#category').val() != ''){
                    $.ajax({
                        type: "GET",
                        url: "/searchitems/year.json",
                        data: "data",
                        dataType: "json",
                        success: function(response) {
                            $.each(response, function(key, value) {
                                if (key == $('#modelo').val()) {
                                    $.each(value, function(k, year) {
                                        $('#year').append('<option value="' + year + '">' + year + '</option>');
                                    });
                                }
                            });
                            $('.uper-form').fadeOut();
                        }
                    });
                }else{
                    $.ajax({
                        type: "GET",
                        url: "/searchitems/year_only.json",
                        data: "data",
                        dataType: "json",
                        success: function(response) {
                            $.each(response, function(key, value) {
                                if (key == $("#modelo option:selected").html()) {
                                    $.each(value, function(k, year) {
                                        $('#year').append('<option value="' + k + '">' + year + '</option>');
                                    });
                                }
                            });
                            $('.uper-form').fadeOut();
                        }
                    });
                }
            });



            /* $('#marca').change(function(e) {
                e.preventDefault();
                $('#modelo').empty();
                $('#modelo').append('<option value="">Modelos</option>');
                $('.uper-form').fadeIn();
                $.ajax({
                    type: "GET",
                    url: "/nipon_modelos/patch/modelos?p=nipon&marca=" + $(this).find("option:selected").text(),
                    data: "data",
                    dataType: "json",
                    success: function(response) {

                        var id_marca = "<?php if (isset($_GET['nipon_modelo']) && $_GET['nipon_modelo'] != '') {
                                            echo $_GET['nipon_modelo'];
                                        } ?>";
                        $.each(response, function(indexInArray, valueOfElement) {
                            console.log(valueOfElement.Id);
                            console.log(id_marca);
                            if (valueOfElement.Id == id_marca) {
                                $('#modelo').append('<option selected="selected" value="' + valueOfElement.Id + '">' + valueOfElement.Modelo + '</option>');
                            } else {
                                $('#modelo').append('<option value="' + valueOfElement.Id + '">' + valueOfElement.Modelo + '</option>');
                            }
                        });
                        $('.uper-form').fadeOut();

                    }
                });
            }); */




            $(".btn-buscador-home").on("click", function(e){
                url="";
                e.preventDefault();
                if($('#category').val()){
                    url= "/" + $("#category").val()+'.html'; 
                    if($('#marca').val()){
                        url= url+"?nipon_marca=" + $("#marca option:selected").html(); 
                    }
                    if($('#modelo').val()){
                        url= url+"&nipon_modelo=" + $("#modelo option:selected").html(); 
                    }
                    if($('#year').val()){
                        url= url+"&nipon_years=" + $("#year option:selected").html(); 
                    }
                }else{
                    url = "/catalogsearch/advanced/result/";
                    if($('#marca').val()){
                        url= url+"?nipon_marca=" + $("#marca").val(); 
                    }
                    if($('#modelo').val()){
                        url= url+"&nipon_modelo=" + $("#modelo").val(); 
                    }
                    if($('#year').val()){
                        url= url+"&nipon_years=" + $("#year").val(); 
                    }
                }
                
                window.location.href = url;
            });

        });
    </script>

    <?php if (isset($_GET['nipon_marca']) && $_GET['nipon_marca'] != '') { ?>
        <script>
            require(["jquery"], function($) {
                $('#marca').trigger('change');
            });
        </script>
    <?php } ?>



<?php //}  ?>