<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title">Ctacorriente - Url</span>
    </div>
    <div class="admin__page-section-content">
        <?php
        //$item = $block->getCtacorrienteUrl();
	    //echo $item->getIncrementId() . " || "; ?>
        <a href="<?php //echo $item->getUrl();?>" target="_blank"> Ver detalle de la Orden de Compra en SAP Ctacorriente.</a>
    </div>
</section>
