<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

/* 
    echo $this->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('custom_account_tab')
->toHtml(); */

$customer_data = $block->getData('customer_hist');
$historial = $customer_data["Response"];

?>
<div class="row">
    <div class="col-lg-12 col-xs-12">
        <div class="box text-center margin-bottom30">
            <h3>HISTORIAL DE NOTAS DE CREDITO</h3>
        </div>
    </div>
    <div class="clearfix visible-sm"></div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="table-responsive historial-pedidos">
            <table id="example" class="display table table-striped"" cellspacing="0" width="100%" style="font-size:12px">
                <thead>
                    <tr>
                        <th>Documento</th>
                        <th>Fecha</th>
                        <!--th>Numero Sap</th-->
                        <!--th>Numero Factura</th-->
                        <th>Folio</th>
                        <th>Cliente</th>
                        <th>Direccion</th>
                        <th>Comuna</th>
                        <th>Ciudad</th>
                        <!--th>Codigo Vendedor</th-->
                        <!--th>Vendedor</th-->
                        <th>Monto</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($historial as $item):?>
                    <tr>
                        <td style="vertical-align: middle;text-align: center;cursor: pointer;">
                            <a class="generate-doc" data-folio="<?php echo $item["Folio"]; ?>">
                                <?php echo $item["Documento"];?> &nbsp;&nbsp; &nbsp;&nbsp;<i class="fas fa-file-download fa-2x"></i>
                            </a>
                            <a id="<?php echo $item["Folio"]?>" href="" style="display:none;" target="_blank">
                                <?php echo $item["Documento"];?> &nbsp;&nbsp; &nbsp;&nbsp;<i class="fas fa-file-invoice fa-2x"></i>
                            </a>
                        </td>
                        <td>
                            <span style="display:none"><?php echo date("Ymd", strtotime($item["Fecha Documento"]));?></span>
                            <?php echo date("d-m-Y", strtotime($item["Fecha Documento"]));?>    
                        </td>
                        <!--td><?php echo $item["NumeroInternoSAP"]?></td-->
                        <!--td><?php echo $item["NumeroFacturaSAP"]?></td-->
                        <td><?php echo $item["Folio"]?></td>
                        <td><?php echo utf8_decode($item["NombreCliente"]); ?></td>
                        <td><?php echo utf8_decode($item["Direccion"]); ?></td>
                        <td><?php echo utf8_decode($item["Comuna"]); ?></td>
                        <td><?php echo utf8_decode($item["Ciudad"]); ?></td>
                        <!--td><?php echo $item["CodigoVendedor"] ?></td-->
                        <!--td><?php echo utf8_decode($item["Vendedor"]); ?></td-->
                        <td><?php echo number_format($item["Monto"], 0, ',', '.');?></td>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
require([
    "jquery",
    "Customcode_Docs/js/jquery.dataTables.min"
], function($){
    /* $(document).ready(function () {
        $('#example').DataTable( {
            "pagingType": "full_numbers"
        } );
    }); */
    $(document).ready(function() {
        $('#example').DataTable( {
            language: {
                "decimal": "",
                "emptyTable": "No hay información",
                "info": "Mostrando _START_ a _END_ de _TOTAL_ Registros",
                "infoEmpty": "Mostrando 0 to 0 of 0 Registros",
                "infoFiltered": "(Filtrado de _MAX_ total registros)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Mostrar _MENU_ Registros",
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "search": "Buscar:",
                "zeroRecords": "Sin resultados encontrados",
                "paginate": {
                    "first": "Primero",
                    "last": "Ultimo",
                    "next": "Siguiente",
                    "previous": "Anterior"
                }
            },
            "order": [[ 1, "desc" ]]
        });
    });
});
</script>

<script>
require([
    "jquery",
], function($){
	$(".generate-doc").on("click", function(event){
        event.preventDefault();
        $(this).find( 'i' ).removeClass();
        $(this).find( 'i' ).addClass( "fas fa-cog fa-spin fa-2x" ); 
        $(this).css("color","#e3332d"); 
        console.log("Folio: ", $(this).data("folio"));
        element = $(this);
        $.get("/docs/customer/factura/", { folio:$(this).data("folio") }, function(data){
            console.log("URL: ",data);
            if(data){
                element.hide();
                $("#"+element.data("folio")).attr("href", data);
                $("#"+element.data("folio")).show();
                $("#"+element.data("folio")).css("color","#01388a"); 
            }
        });
    });
	
});
</script>